services:
  etemptation_lauch_ticket:
    build: .
    image: harbor.ville-noumea.nc/infra/etemptation_lunch_ticket
    container_name: etemptation_lunch_ticket
    env_file:
      - .env
    restart: "no"
