name: Build image

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  oci-build:
    uses: DSI-Ville-Noumea/ghactions/.github/workflows/oci-build.yml@v1.5.0
    with:
      cr_prefix: harbor.ville-noumea.nc/infra
    secrets:
      cr_host: ${{ secrets.HARBOR_HOSTNAME }}
      cr_username: ${{ secrets.HARBOR_USERNAME }}
      cr_token: ${{ secrets.HARBOR_TOKEN }}
